spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:campus_imaotai}?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  #redis配置
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:26379}
    database: ${REDIS_DATABASE:5}
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password:  ${REDIS_PASSWORD:123456}